### ISSUE TITLE
Ubuntu 22.04 compile error: no member named 'filesystem' in namespace 'std'

### ISSUE THREAD

**Issue by andimik** [deeptho/blindscan#2] opened 2022-06-30 21:35 UTC
Could you tell me, if I need an additional package under Ubuntu 22.04, as I get the following error when compiling:

```
$ cmake ..
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andreas/apps/blindscan/build
```

```
$ make
Consolidate compiler generated dependencies of target neumo-blindscan
[ 16%] Building CXX object src/CMakeFiles/neumo-blindscan.dir/neumo-blindscan.cc.o
/home/andreas/apps/blindscan/src/neumo-blindscan.cc:1649:8: warning: decomposition declarations are a C++17 extension [-Wc++17-extensions]
                auto [found_freq, bw2] =
                     ^~~~~~~~~~~~~~~~~
/home/andreas/apps/blindscan/src/neumo-blindscan.cc:1723:11: warning: decomposition declarations are a C++17 extension [-Wc++17-extensions]
                                        auto [found_freq, bw2] = getinfo(fpout_bs, fefd, pol_is_v, 0, band);
                                             ^~~~~~~~~~~~~~~~~
/home/andreas/apps/blindscan/src/neumo-blindscan.cc:1948:10: error: no member named 'filesystem' in namespace 'std'
        if(std::filesystem::exists("/sys/module/dvb_core/info/version")) {
           ~~~~~^
2 warnings and 1 error generated.
make[2]: *** [src/CMakeFiles/neumo-blindscan.dir/build.make:76: src/CMakeFiles/neumo-blindscan.dir/neumo-blindscan.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: src/CMakeFiles/neumo-blindscan.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

```
$ c++ --version
c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
```

```
$ g++ --version
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
```

**Comment by andimik** [comment] 2022-06-30 21:46
Well, I found out that I just need to comment out these lines, then I can compile and install `neumo-blindscan` and `neumo-tune`


neumo-blindscan.cc#1948

```
//	if(std::filesystem::exists("/sys/module/dvb_core/info/version")) {
//		printf("Blindscan drivers found\n");
//	} else {
//		printf("!!!!Blindscan drivers not installed!!!\n");
//		exit(1);
//	}
```

neumo-tune.cc#1321

```
//	if(std::filesystem::exists("/sys/module/dvb_core/info/version")) {
//		printf("Blindscan drivers found\n");
//			has_blindscan = true;
//	} else {
//		printf("!!!!Blindscan drivers not installed  - only regular tuning will work!!!!\n");
//		options.algo = algo_t::WARM;
//	}
```

```
$ make
[ 16%] Building CXX object src/CMakeFiles/neumo-blindscan.dir/neumo-blindscan.cc.o
/home/andreas/apps/blindscan/src/neumo-blindscan.cc:1649:8: warning: decomposition declarations are a C++17 extension [-Wc++17-extensions]
                auto [found_freq, bw2] =
                     ^~~~~~~~~~~~~~~~~
/home/andreas/apps/blindscan/src/neumo-blindscan.cc:1723:11: warning: decomposition declarations are a C++17 extension [-Wc++17-extensions]
                                        auto [found_freq, bw2] = getinfo(fpout_bs, fefd, pol_is_v, 0, band);
                                             ^~~~~~~~~~~~~~~~~
2 warnings generated.
[ 33%] Building CXX object src/CMakeFiles/neumo-blindscan.dir/dvb_strings.cc.o
[ 50%] Linking CXX executable neumo-blindscan
[ 50%] Built target neumo-blindscan
[ 66%] Building CXX object src/CMakeFiles/neumo-tune.dir/neumo-tune.cc.o
/home/andreas/apps/blindscan/src/neumo-tune.cc:1263:8: warning: decomposition declarations are a C++17 extension [-Wc++17-extensions]
                auto [found_freq, bw2] = getinfo(NULL, fefd, pol_is_v, frequency - options.search_range / 2, band);
                     ^~~~~~~~~~~~~~~~~
1 warning generated.
[ 83%] Building CXX object src/CMakeFiles/neumo-tune.dir/dvb_strings.cc.o
[100%] Linking CXX executable neumo-tune
[100%] Built target neumo-tune

```

**Comment by deeptho** [comment] 2022-07-07 20:50
You should compile this with clang, not with g++

**Comment by deeptho** [comment] 2022-08-06 11:21
Closing. Probable reason: c-compiler too old

**Closed as completed by deeptho** 2022-08-06 11:21 UTC

**Comment by helmet21** [comment] 2022-10-06 06:32
Am seeing the same problem on Ubuntu 22.04.

Tried changing references from 'clang++' to 'c++' in the cmakefiles.

```
$ grep -r "CMAKE_CXX_COMPILER clang++"
src/CMakeLists.txt:    SET (CMAKE_CXX_COMPILER clang++)
CMakeLists.txt:    SET (CMAKE_CXX_COMPILER clang++)
```
Which gave this error:
```
$ make
Consolidate compiler generated dependencies of target neumo-blindscan
[ 16%] Building CXX object src/CMakeFiles/neumo-blindscan.dir/neumo-blindscan.cc.o
/home/helmet/repos/blindscan/src/neumo-blindscan.cc: In function ‘std::tuple<int, int> getinfo(FILE*, int, bool, int, int)’:
/home/helmet/repos/blindscan/src/neumo-blindscan.cc:547:70: warning: taking address of packed member of ‘dtv_property’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  547 |         uint32_t* isi_bitset = (uint32_t*)cmdseq.props[i++].u.buffer.data; // TODO: we can only return 32 out of 256
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/helmet/repos/blindscan/src/neumo-blindscan.cc:552:55: warning: taking address of packed member of ‘dtv_property’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  552 |                 (uint32_t*)cmdseq.props[i++].u.buffer.data; // TODO: we can only return 32 out of 256 entries...
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
[ 33%] Building CXX object src/CMakeFiles/neumo-blindscan.dir/dvb_strings.cc.o
[ 50%] Linking CXX executable neumo-blindscan
[ 50%] Built target neumo-blindscan
Consolidate compiler generated dependencies of target neumo-tune
[ 66%] Building CXX object src/CMakeFiles/neumo-tune.dir/neumo-tune.cc.o
/home/helmet/repos/blindscan/src/neumo-tune.cc: In function ‘std::tuple<int, int> getinfo(FILE*, int, bool, int, int)’:
/home/helmet/repos/blindscan/src/neumo-tune.cc:494:59: error: cannot bind packed field ‘(cmdseq.dtv_properties::props + ((sizetype)(((long unsigned int)(cmdseq.dtv_properties::num - 1)) * 76)))->dtv_property::u.dtv_property::<unnamed union>::constellation’ to ‘dtv_fe_constellation&’
  494 |                 auto& cs = cmdseq.props[cmdseq.num - 1].u.constellation;
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/helmet/repos/blindscan/src/neumo-tune.cc:526:70: warning: taking address of packed member of ‘dtv_property’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  526 |         uint32_t* isi_bitset = (uint32_t*)cmdseq.props[i++].u.buffer.data; // TODO: we can only return 32 out of 256
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/home/helmet/repos/blindscan/src/neumo-tune.cc:533:48: error: cannot bind packed field ‘(cmdseq.dtv_properties::props, (cmdseq.dtv_properties::props + ((sizetype)(((long unsigned int)(i ++)) * 76))))->dtv_property::u.dtv_property::<unnamed union>::constellation’ to ‘dtv_fe_constellation&’
  533 |                 auto& cs = cmdseq.props[i++].u.constellation;
      |                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/neumo-tune.dir/build.make:76: src/CMakeFiles/neumo-tune.dir/neumo-tune.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:126: src/CMakeFiles/neumo-tune.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
So tried symbolic links
```
sudo mv /usr/bin/clang++ /usr/bin/clang++tmp
sudo ln -s /usr/bin/c++ /usr/bin/clang++
```
Which gave the same error.

Am running
```
$ clang++ --version
Ubuntu clang version 14.0.0-1ubuntu1

$ c++ --version
c++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0

$ uname -a
Linux t470 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Update**: I'm guessing that this line from the original post shows that the compile is breaking because the driver hasn't actually been installed.
```
/home/andreas/apps/blindscan/src/neumo-blindscan.cc:1948:10: error: no member named 'filesystem' in namespace 'std'
        if(std::filesystem::exists("/sys/module/dvb_core/info/version")) {
           ~~~~~^
```
So back to debugging media_build...

**Comment by deeptho** [comment] 2022-10-17 21:56
Yes, this cannot work. Like I wrote above: the code needs to be compiled with clang++
Instead you seem to make the command clang++ call c++ (which is g++) to force the use 
of g++ which probably will not work

On ubuntu 20.04 compilation works perfectly.
I have not tried 22.04 yet.

**Comment by juankr10s** [comment] 2022-12-05 04:28
what clang++ version do you use for compile?

**Comment by andimik** [comment] 2023-01-09 20:10
> the code needs to be compiled with clang++

Unfortunately you did not tell us how to do it. After several researches I found it:

`cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++`

I've sent you a PR.

**Comment by deeptho** [comment] 2023-01-10 19:32
The only thing you need to do is install the clang++ compiler. It will then be used.

**Comment by helmet21** [comment] 2023-04-06 15:12
I can confirm that it is not enough to install clang++ on Ubuntu 22.04 but the command proposed by @andimik solved it for me.

**Comment by deeptho** [comment] 2023-04-17 19:39
It still means something is wrong regarding clang++ installation. 
There is no need to specify the compiler on the command line
